# Site settings
title: PhosFate
email: ochoa@ebi.ac.uk
description: An Atlas of Human Quantitative Phosphoregulation
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://evocellnet.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

include:
  - .nojekyll

exclude:
  - "bower_components"
  - "bower.json"
  - "node_modules"
  - "package.json"
  - "Gruntfile.coffee"
  - "Rakefile"
  - "Vagrantfile"
  - "bootstrap_apache.sh"
  - "bootstrap_shiny.sh"
  
assets:
  baseurl: ""
  cache: false
  cdn: https://cdn.example.com
  skip_prefix_with_cdn: false
  prefix: "/assets"
  assets:
    - "*.png"
    - "bundle.css"
  digest: true
  sources:
    - "_assets/js"
    - "_assets/img"
    - "_assets/css"
    - "_assets/css/vendor"
    - "_assets/js/vendor"
  features:
    liquid: true
    automatic_img_size: true
    automatic_img_alt : true
